site_name: Neural Network
repo_url: https://github.com/PREPONDERANCE/Neural-Network
repo_name: Neural Network Learning

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate